{{
    config(
        materialized= 'table'
    )
}}

with konp as (
    select 
        CASE WHEN INDEX IS NULL THEN -99 ELSE INDEX END AS INDEX,
        CASE WHEN SKTOF IS NULL THEN 'NA' ELSE SKTOF END AS SKTOF,
        CASE WHEN KNUMA IS NULL THEN 'NA' ELSE KNUMA END AS KNUMA,
        CASE WHEN KONWA IS NULL THEN 'NA' ELSE KONWA END AS KONWA,
        CASE WHEN KSCHL IS NULL THEN 'NA' ELSE KSCHL END AS KSCHL,
        CASE WHEN KSLVL IS NULL THEN 'NA' ELSE KSLVL END AS KSLVL,
        CASE WHEN KSTBW IS NULL THEN 0 ELSE KSTBW END AS KSTBW,
        CASE WHEN BEGDA IS NULL THEN '1900-01-01' ELSE BEGDA END AS BEGDA,
        CASE WHEN ENDDA IS NULL THEN '1900-01-01' ELSE ENDDA END AS ENDDA,
        CASE WHEN VAFR IS NULL THEN '1900-01-01' ELSE VAFR END AS VAFR,
        CASE WHEN VATO IS NULL THEN '1900-01-01' ELSE VATO END AS VATO,
        CURRENT_DATE() AS LAST_MODIFIED
    from {{ source('snf_staging','KONP') }}
)
SELECT * FROM konp