{{
    config(
        materialized= 'table'
    )
}}

with TCURC as (
    select
        CASE WHEN INDEX IS NULL THEN -99 ELSE INDEX END AS INDEX,
        CASE WHEN STOREID IS NULL THEN 'NA' ELSE STOREID END AS STOREID,
        CASE WHEN STORENAME IS NULL THEN 'NA' ELSE STORENAME END AS STORENAME,
        CASE WHEN CITY IS NULL THEN 'NA' ELSE CITY END AS CITY,
        CASE WHEN ADDRESS IS NULL THEN 'NA' ELSE ADDRESS END AS ADDRESS,
        CASE WHEN ZIP IS NULL THEN 'NA' ELSE ZIP END AS ZIP,
        CASE WHEN COUNTRYCODE IS NULL THEN 'NA' ELSE COUNTRYCODE END AS COUNTRYCODE,
        CASE WHEN COUNTRY IS NULL THEN 'NA' ELSE COUNTRY END AS COUNTRY,
        CASE WHEN LINK IS NULL THEN 'NA' ELSE LINK END AS LINK,
        CASE WHEN CHANNEL IS NULL THEN 'NA' ELSE CHANNEL END AS CHANNEL,
        CURRENT_DATE() AS LAST_MODIFIED
    from {{ source('snf_staging','TCURC') }}
)
select * from TCURC